# NB this is a modified version of:
#      https://github.com/linuxkit/linuxkit/blob/79b32dc2c74a7cd2ef56c834c771b978a5ed16a7/examples/sshd.yml
#      https://github.com/linuxkit/linuxkit/blob/79b32dc2c74a7cd2ef56c834c771b978a5ed16a7/examples/logging.yml
kernel:
  image: linuxkit/kernel:5.10.39
  # NB tty0 (or console) represent the current virtual terminal.
  cmdline: "console=tty1"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
  - linuxkit/memlogd:9b0e8a5b3f67672234170d88833163caf7898984
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
  - name: rngd1
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
    command: ["/sbin/rngd", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:bdabfe138f05f7d48396d2f435af16f5a6ccaa45
  - name: dhcpcd
    image: linuxkit/dhcpcd:1033f340e2d42f86a60aab70752346f0045ea388
  - name: logwrite
    image: linuxkit/logwrite:e64e0f06e485e3542b58f3517da3bc13f246d208
  - name: kmsg
    image: linuxkit/kmsg:df84eda2a82d5e24ddfe241831af3efb13a1a557
  - name: getty
    image: linuxkit/getty:ed32c71531f5998aa510847bb07bd847492d4101
    env:
      - INSECURE=true
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
  - name: sshd
    image: linuxkit/sshd:add8c094a9a253870b0a596796628fd4ec220b70
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
  - name: hello
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while true; do echo hello $(date); sleep 1; done"]
files:
  # see https://github.com/linuxkit/linuxkit/blob/master/docs/faq.md#enabling-and-controlling-containerd-logs
  - path: etc/containerd/runtime-config.toml
    contents: |
      cliopts="--log-level debug"
      stderr="/var/log/containerd.log"
      stdout="/var/log/containerd.out.log"
    mode: "0644"
  - path: root/.ssh/authorized_keys
    contents: |
      # from https://raw.github.com/hashicorp/vagrant/master/keys/vagrant.pub
      ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    mode: "0600"
  - path: etc/profile.d/local.sh
    contents: |
      alias logread='/proc/1/root/usr/bin/logread'
      alias l='ls -lF'
      alias ll='l -a'
    mode: "0644"
